### ISSUE TITLE
cannot print already installed PTable 

### ISSUE THREAD

**Issue by dd-jy** [raimon49/pip-licenses#111]
If one of the project's dependencies is the PTable, it cannot be printed in the result of pip-licenses.
Please fix it.

**Comment by raimon49** [comment]
Yes, pip-licenses itself depends on PTable, so it is intentionally not outputting.

Could you try the `--with-system` option?

**Comment by dd-jy** [comment]
I thought the option was meant to not output only setuptools and pip.
It prints the pip-licenses and PTable also. Thank you.
