### ISSUE TITLE
Will `pip-licenses` fail if one of my dependencies has a non-permissive license?

### ISSUE THREAD

**Issue by John15321** [raimon49/pip-licenses#125]
Will `pip-licenses` fail if one of my dependencies has a non-permissive license?
Im looking to use it in a CI setting so I would like it to return something other than `0` in a case like that.

**Comment by raimon49** [comment]
Please read the documentation for the `--fail-on` option.
https://github.com/raimon49/pip-licenses#option-fail-on

**Comment by raimon49** [comment]
This issue is deemed resolved.
