### ISSUE TITLE
[--with-license-file] Fails to extract license file on Black 22.10.0

### ISSUE THREAD

**Issue by roniemartinez** [raimon49/pip-licenses#126]
For new versions of `black`, the license file has been moved to `licenses` folder. When using `--with-license-file`, the result is `UNKNOWN`

<img width="196" alt="image" src="https://user-images.githubusercontent.com/2573537/196808316-bc4e83d3-c376-4039-9987-045550f70733.png">

**Comment by raimon49** [comment]
@roniemartinez Thanks for the report.

We have released a version that fixes this problem. Could you try it?

```bash
pip install -U pip-licenses==3.5.5
```

**Comment by roniemartinez** [comment]
@raimon49 It is working fine now. Thank you.
