### ISSUE TITLE
"pip-licenses" is missing in output of "pip-licenses --with-system"

### ISSUE THREAD

**Issue by philer-jambit** [raimon49/pip-licenses#135]
I've made sure that pip-licenses is installed in the same environment that I'm running the command in. It is the only package missing in the output despite using the `--with-system` flag – `prettytable` and `wcwidth` are included.
I believe this happens since version 4.0.0.

```sh
$ pip --version
pip 22.3.1 from /home/***/.virtualenvs/***/lib/python3.10/site-packages/pip (python 3.10)

$ pip freeze | grep pip-licenses
pip-licenses==4.0.0

$ which pip-licenses
/home/***/.virtualenvs/***/bin/pip-licenses

$ pip-licenses --with-system | grep pip-licenses
```
(The final command produces no output)

**Comment by raimon49** [comment]
@philer-jambit Thanks for the detailed report.

This bug is due to my lack of review during the v 4.0.0 release process.

I just uploaded v 4.0.1 to PyPI. can you try it?
https://pypi.org/project/pip-licenses/4.0.1/

**Comment by philer-jambit** [comment]
Hey, I gave it a try, looks like it's working correctly now.

Thanks for the quick response & fix!
