### ISSUE TITLE
Expose maintainers

### ISSUE THREAD

**Issue by stefan6419846** [raimon49/pip-licenses#144]
Some packages do not have the `author` field set, but the `maintainer` one (example: https://github.com/opencv/opencv-python/blob/b776e5ce9f164600a1bd05178a058272122bf02a/setup.py#L272). Exposing the maintainer as well would allow users to work with the maintainer value if the author value would be empty otherwise.

**Comment by raimon49** [comment]
Good suggestion.

For example, would you prefer `OpenCV Team(maintainer)` as the output result, or simply `OpenCV Team` ?

**Comment by stefan6419846** [comment]
This depends on the output format in my opinion. For me, a new key `maintainer` returned by `piplicenses.get_packages` would be sufficient as I am rendering the results myself and can decide on how I want to display maintainers. I am not sure about the actual rendered output though, as I am not actually using it.

**Comment by raimon49** [comment]
Then, it might be a good idea to output a new column like `--with-maintainers`.

Think of something and prepare a release candidate version.

**Comment by raimon49** [comment]
@stefan6419846 A release is planned to resolve this suggestion.

The next release candidate version has been uploaded to PyPI.
https://pypi.org/project/pip-licenses/4.2.0rc1/

Install it in your environment and make sure it is working as expected.
```bash
pip install pip-licenses==4.2.0rc1
```

There is some time before the official release. Feedback is welcome.

**Comment by stefan6419846** [comment]
I just did a quick test and could everything seems to work as expected. Thanks.
