### ISSUE TITLE
Treat `-` and `_` as equivalent in package names

### ISSUE THREAD

**Issue by KennyChenBasis** [raimon49/pip-licenses#160]
`pip` treats `-` and `_` as equivalent, but `pip-licenses` differentiates between the two when using the `-p` flag. Having `pip-licenses` also treat `-` and `_` as equivalent makes it easier to work with.

In my particular use case, I have a venv that contains packages from a `requirements.txt` and also additional packages that I don't want licenses of. I then passed the packages in the `requirements.txt` to `pip-licenses -p` and was surprised when the license for `typing-extensions` wasn't found. However, passing `typing_extensions` instead to `pip-licenses` works.

`requirements.txt` in this form can be created from, e.g. `pipenv requirements`.

**Comment by raimon49** [comment]
@KennyChenBasis We have shipped version 4.3.1, which fix this issue.
https://pypi.org/project/pip-licenses/4.3.1/

Please check if it works as you expect using v4.3.1.
```bash
pip install pip-licenses=="4.3.1"
```

**Comment by KennyChenBasis** [comment]
Looks like it works; thanks for the timely response and fix!

**Comment by ogencoglu** [comment]
How do we list the licenses from requirements.txt? 

`pip-licenses -p requirements.txt` returns an empty list in venv even though those libraries are installed in venv.

**Comment by stefan6419846** [comment]
`pip-licenses -p requirements.txt` yields no results as there is no package `requirements.txt`. From the description of the `-p` parameter:

> only include selected packages in output

So you would have to pass your desired packages by their name explicitly or find a Shell-specific way to extract the package names from your requirements file automatically.
