### ISSUE TITLE
for django-cron library license showing UNKNOWN

### ISSUE THREAD

**Issue by rushikeshiam** [raimon49/pip-licenses#171]
for django-cron library license showing UNKNOWN, but in actual there is license called [MIT license](https://github.com/Tivix/django-cron/blob/master/LICENSE)

**Comment by stefan6419846** [comment]
*pip-licenses* is not license scanner, but a metadata parser. As the corresponding `setup.py` file does not have any license information, *pip-licenses* is not able to return a useful license here: https://github.com/Tivix/django-cron/blob/db653a292d7a6f78e7ed76d22b282371147aa48c/setup.py#L21-L42

If you want *django-cron* to be reported with the correct license, you should probably file an upstream report to add the correct field or trove classifier.

**Comment by raimon49** [comment]
@stefan6419846 Perfect answer. Thank you!

@rushikeshiam Some users utilize `--with-license-file` as an alternative.However, since viewability is difficult, it is necessary to output the data in JSON, etc.
