### ISSUE TITLE
[BUG] Unable to check licences of archived github packages

### ISSUE THREAD

**Issue by ryan-cpi** [raimon49/pip-licenses#189]
As the title says the pip-licenses checker reports back a licence of UNKNOWN for archived packages.
For example, these show up as unknown for us when its clearly marked as MIT
 - https://github.com/markfinger/optional-django
 - https://github.com/markfinger/python-npm

**Comment by stefan6419846** [comment]
`pip-licenses` only considers the package metadata as provided by the maintainer, which just does not have a license in neither https://github.com/markfinger/optional-django/blob/master/setup.py nor https://github.com/markfinger/python-npm/blob/master/setup.py If you want to determine the license from hints like the LICENSE file (as GitHub does), you will have to use a fully-fledged license scanner `pip-licenses` is NOT.
