### ISSUE TITLE
Summary table and raw results are inconsistent

### ISSUE THREAD

**Issue by jameslamb** [raimon49/pip-licenses#29]
While working with `pip-licenses` today, I noticed an inconsistency between raw and summary output.

Steps to reproduce:

```
echo "awscli" > docker/requirements.txt
docker build -t myapp-licenses -f .
```

Output of `docker run --rm myapp-licenses`:

```
Name             Version   License
 PyYAML           3.13      MIT License
 awscli           1.16.140  Apache Software License
 botocore         1.12.130  Apache Software License
 colorama         0.3.9     BSD License
 docutils         0.14      Public Domain, Python Software Foundation License, BSD License, GNU General Public License (GPL)
 jmespath         0.9.4     MIT License
 pyasn1           0.4.5     BSD License
 python-dateutil  2.8.0     BSD License, Apache Software License
 rsa              3.4.2     Apache Software License
 s3transfer       0.2.0     Apache Software License
 six              1.12.0    MIT License
 urllib3          1.24.1    MIT License
```

Output of `docker run --rm myapp-licenses --summary`

```
 Count  License
 1      ASL 2
 3      Apache License 2.0
 2      BSD
 1      Dual License
 4      MIT
 1      public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)
```

Looking at the non-summary results, I'd expected the results from `--summary` to be

```
 Count  License
 4     Apache Software License
 1      BSD License, Apache Software License
 2      BSD
 4      MIT
 1      public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)
```

I cannot figure out from the source code of `piplicenses.py` where things like converting "BSD License, Apache Software License" to "Dual License" are happening, but I propose that this inconsistency is problematic. If you use `pip-licenses` to scan for dependency licenses that your organization wants to avoid (as many orgs do with GPL code), not all "Dual License" projects are equally worthy of attention.

**Comment by raimon49** [comment]
Please use `docker run --rm myapp-licenses --from-classifier --summary`. The built-in Docker environment implicitly uses the `--from-classifier` option.

"Dual License" is output when --from-classifier option is not specified.

**Comment by jameslamb** [comment]
Ah ok, I see that now! Ok then yeah this issue can probably be closed. Thanks!
