### ISSUE TITLE
Docs: Support for transient dependencies?

### ISSUE THREAD

**Issue by fkromer** [raimon49/pip-licenses#41]
When looking at the [usage example](https://github.com/raimon49/pip-licenses#usage) it seems like `pip-license` does not support [transitive dependencies](https://en.wikipedia.org/wiki/Transitive_dependency). Does `pip-license` show licenses of transitive dependencies?

**Comment by raimon49** [comment]
Any package installed as a transitive dependency via `pip install` command in your environment will be displayed.

For example, packages described in [the install_requires of flask](https://github.com/pallets/flask/blob/master/setup.py) is displayed

```bash
$ python -m venv flask
$ source flask/bin/activate

(flask) $ pip install flask pip-licenses
(flask) $ pip-licenses
 Name          Version  License
 Click         7.0      BSD
 Flask         1.1.1    BSD-3-Clause
 Jinja2        2.10.3   BSD-3-Clause
 MarkupSafe    1.1.1    BSD-3-Clause
 Werkzeug      0.16.0   BSD-3-Clause
 itsdangerous  1.1.0    BSD
```
