### ISSUE TITLE
Show licenses of app/lib runtime dependencies only?

### ISSUE THREAD

**Issue by fkromer** [raimon49/pip-licenses#42]
I'm using `pipenv` (`Pipfile`, `Pipfile.lock`) to manage Python package dependencies. In the venv during development there are included all dependencies including the `--dev` dependencies. Would be great if one could easily check the licenses of the packages used during app/library runtime only.

**Comment by raimon49** [comment]
@fkromer Thank you for your suggestion. It ’s a good idea.

However, currently `pip-licenses` does not support `Pipfile`, `Pipfile.lock` parsing.

If you want to see a list of licenses for both production and dev environments, create both production ( `pipenv install`) and dev ( `pipenv install --dev` ), and run `pip-licenses` in each.
