### ISSUE TITLE
--output-file option

### ISSUE THREAD

**Issue by johnthagen** [raimon49/pip-licenses#46]
`pip-licenses` is really great, thanks!

Would it be possible to add a command line argument that wrote the resulting output to a file instead of being `print`ed to the screen? Terminal redirection is not always available (such as in a `tox` environment).

Example:

```bash
$ pip-licenses --format=rst --output-file=my_output.rst
```

**Comment by raimon49** [comment]
It's a good proposal.

I will try to implement this feature.

**Comment by johnthagen** [comment]
And specifically, I think it would be best if it were possible to `print` *and* output to the file. Perhaps `--output-file` just additionally writes the output to a file.

**Comment by raimon49** [comment]
@jameslamb This option was supported in version 1.17.0.

https://pypi.org/project/pip-licenses/1.17.0/

Thank you for your feature request.
