### ISSUE TITLE
Add --format=plain-vertical format

### ISSUE THREAD

**Issue by johnthagen** [raimon49/pip-licenses#49]
We used `pip-licenses --with-license-file --format=plain` to try to generate something like Angular CLI's https://angular.io/3rdpartylicenses.txt format.

The issue with `pip-licenses`'s plain format is that it still tries to line things up horizontally, which can make it difficult to read in a browser. Also we noticed that some license files with special characters broke `pip-licenses` attempt to properly align the licenses.

Could a new format by added called `--format=plain-vertical` that puts the information in a vertical format similar to Angular CLI's generated output? This would be very useful.

**Comment by raimon49** [comment]
As you say, JavaScript(npm) community outputs lists in this format.

I cannot guarantee the implementation, but I accept it as a feature request.
