### ISSUE TITLE
Add ability to suppress license file path

### ISSUE THREAD

**Issue by johnthagen** [raimon49/pip-licenses#50]
Currently if the user adds `--with-license-file` the full absolute path of the license file is included in the output. If the user wants to distribute this license information file with their software, paths that include their user name on the system where `pip-licenses` was run are leaked into the output.

It would be very helpful if the path to the license file path could be suppressed from the output to avoid this.

**Comment by johnthagen** [comment]
Related to #49

**Comment by raimon49** [comment]
Certainly I think that I also have users who do not want to see the absolute path.

Adding this feature is easier than #49. I might only release this feature  first.

**Comment by johnthagen** [comment]
@raimon49 Sounds great! Being able to suppress the path would also greatly reduce the horizontal space used, so the motivation behind #49 would somewhat solved by this too.

**Comment by johnthagen** [comment]
A potential name for the argument could be: `--no-license-path`

**Comment by raimon49** [comment]
@jameslamb Option `--no-license-path` was supported in version 2.0.0.
https://pypi.org/project/pip-licenses/2.0.0/

Thanks for the suggestion.

**Comment by jameslamb** [comment]
I think you meant @johnthagen

**Comment by raimon49** [comment]
@jameslamb Oh!  Thank you!

ping @johnthagen
