### ISSUE TITLE
pip-licenses does not support packages with license files named "COPYING"

### ISSUE THREAD

**Issue by johnthagen** [raimon49/pip-licenses#59]
It is somewhat common (as I've found trying to ensure that all of my packages have license files in a `pip-licenses` report) for packages to use `COPYING` as their license file name.

See this reference in a `setuptools` issue: https://github.com/pypa/setuptools/issues/1636#issue-399017234

> In the same way that README files are automatically grafted into the source distribution, it would be nice if `LICENSE` / `COPYING` files were also included by **default**

Currently `pip-licenses` cannot find these license files due to this code:

https://github.com/raimon49/pip-licenses/blob/742c814630638efe27b3730c37c2d281af9f9261/piplicenses.py#L138

Could this be expanded to include `COPYING*` as well?

Example:

- [`jsonschema`](https://github.com/Julian/jsonschema/blob/master/COPYING)

**Comment by raimon49** [comment]
Thanks for the report.

> Could this be expanded to include COPYING* as well?

It is possible to find a match for `LICENSE*` / `COPYING*` in the distribution. Will be implemented soon.
