### ISSUE TITLE
Consider using trove/mixed as default license information source

### ISSUE THREAD

**Issue by johnthagen** [raimon49/pip-licenses#60]
I've learned that trove classifiers are the preferred way to express license type information. See this note for explanation:

- https://github.com/jaraco/skeleton/issues/9#issuecomment-573906949

I believe that the current default for `pip-licenses` `--from` is not ideal (basically it always needs to be changed to get the best license information.

Would you consider changing the default to either `trove` or `mixed`? I personally feel `mixed` is the best default because it will provide the most comprehensive license information and prefer the correct source of truth (the troves).

I find [this ](https://docs.python.org/3.9/distutils/setupscript.html#additional-meta-data)particularly compelling:

> The license field is a text indicating the license covering the package where the license is not a selection from the “License” Trove classifiers. See the Classifier field. Notice that there’s a licence distribution option which is deprecated but still acts as an alias for license.

**Comment by raimon49** [comment]
Yes, your opinion is correct.

pip-licenses started by outputting the `license` field, then supported the output of trove classifiers, and finally implemented mixed mode.

Currently,  I think mixed mode can output the most desirable result.

However, changing the default behavior is a breaking change. I when to release a pip-licenses version 3.0, will probably adopt a mixed mode in default.

**Comment by johnthagen** [comment]
> However, changing the default behavior is a breaking change. I when to release a pip-licenses version 3.0, will probably adopt a mixed mode in default.

Agree, and that plan sounds great! Thanks!
