### ISSUE TITLE
Some packages cause UnicodeDecodeError when attempting to read package info

### ISSUE THREAD

**Issue by Lightslayer** [raimon49/pip-licenses#63]
A workaround solution seems to be add `errors='ignore'` to the `open` call for `license_file_handle` on line 146:

![image](https://user-images.githubusercontent.com/3184694/74509439-6534be00-4ef9-11ea-8723-8abb1b4c2f85.png)

**Comment by raimon49** [comment]
@Lightslayer Thanks for the suggestion.

In the original implementation was not specify `errors='replace'`, `errors` argument is no longer in this commit.
https://github.com/raimon49/pip-licenses/pull/56/commits/63516663b0a33f7041e37d1b1c0ed459968f536c

I will add `ignore` or` replace` to the argument in the next release.
