### ISSUE TITLE
Check for 'LICENCE*' as well

### ISSUE THREAD

**Issue by fladd** [raimon49/pip-licenses#67]
Currently, packages that use British spelling are not recognized.

Example: https://github.com/tqdm/tqdm/

**Comment by raimon49** [comment]
@fladd Oh, thanks for the reporting!

I will fix this issue in the next release.

**Comment by raimon49** [comment]
@fladd Hi, I just shipped the new version 2.2.0.

In 2.2.0, you can handle the file name of British spelling.
