### ISSUE TITLE
Feature Request: Print information about different venv environments.

### ISSUE THREAD

**Issue by soimkim** [raimon49/pip-licenses#75]
[Feature Request] Print information about different venv environments.

Details:
- Print python module information for venvs in different paths in separate scripts.
  (ex- If you pass the path of another venv, you can print it.)

Reasons needed:
- It is necessary to print each python module for multiple venv environments in CI/CD environment.

**Comment by raimon49** [comment]
Thank you for the feature request.

The goal of pip-licenses is to output installed packages "in" the venv environment.

This request looks to me like a problem that needs to be solved outside of the venv environment. This is a problem that should be solved by the way you build your CI/CD pipeline.
