### ISSUE TITLE
feature_request(path): Custom packages path support

### ISSUE THREAD

**Issue by Kristinita** [raimon49/pip-licenses#9]
### 1. Summary

It would be nice, if pip-licenses will support check licenses from custom path.

### 2. Argumentation

**Example**: I use [**Pelican — static site generator**](https://blog.getpelican.com/) and [**plugins for it**](https://github.com/getpelican/pelican-plugins), written by Python. Pelican plugins must [**installed to custom folder**](http://docs.getpelican.com/en/latest/plugins.html) — usually [**`pelican-plugins`**](https://github.com/Kristinita/KristinitaPelican/tree/master/pelican-plugins), not to default `site-packages`. I don't know, how possible check licenses from `pelican-plugins` folder.

### 3. Example of expected behavior

**If**:

    pip-licenses --path output/pelican-plugins

pip-licenses will check licenses from `output/pelican-plugins` folder recursively.

### 4. Not helped

I don't find already existing packages, that solve this problem. For example, I try:

+ [**license_lister**](https://github.com/jonkr/license_lister),
+ [**license_info**](https://pypi.org/project/license-info/),
+ [**plicense**](https://pypi.org/project/plicense/),
+ [**yolk3k**](https://pypi.python.org/pypi/yolk3k),
+ [**pylicense**](https://pypi.org/project/pylicense/).

Thanks.

**Comment by raimon49** [comment]
@Kristinita Thank you for requesting features and proposing behavior.

This package(pip-licenses) is focused on checking the current venv environment. And I am satisfied with the current behavior.

But I can understand your feature request. If when the pip-licenses 2.0.0 was released, might this feature is implemented.

**Comment by raimon49** [comment]
@Kristinita Hi, Kristinita.

I have created a [contribution guidelines](https://github.com/raimon49/pip-licenses/blob/master/CONTRIBUTING.md). And this software wants to focus on output of licenses installed with pip.

Your proposal is attractive. However, it is outside the scope of this software.

For example, how about trying to implement a simple script to find the LICENSE file from your custom folder? [This function added to pip-licenses in the latest version](https://github.com/raimon49/pip-licenses/blob/v-1.11.0/piplicenses.py#L112-L135) will be helpful.

This issue closes, Thank you for the specific proposal.
